### ISSUE TITLE
iOS 11

### ISSUE THREAD

**Issue by saifulapm** [iloveapple1999/Downgrade-A7-Device-to-10.2-10.2.1-with-Blobs#1]
Hello,

I upgraded to iOS 11 from iOS 10.3.3.  But Now It can not be activated. 
Is there any solution to active this iPhone 5S ?
Is there any way to downgrade to iOS 10.3.3 ?

Any solution ? Tethered downgrade or any hack possible ? 

You guys are great developer. Please help me..

**Comment by ProAppleOS** [comment]
Hi,
1. I'm not a developer
2. you can restore with iTunes in DFU mode (search on google)
3. you can't downgrade unfortunately you must be on 10.3.x

**Comment by saifulapm** [comment]
I restored many times but not success. Still activation error..  Anyway Thanks for your response.
